name: setup-env
description: Initializes environment.
outputs:
  node-version:
    value: ${{ steps.detect-node.outputs.version }}
    description: Detected Node version.
runs:
  using: "composite"
  steps:
    - name: Detect Node Version
      id: detect-node
      run: echo "::set-output name=version::$(cat .nvmrc | tr -d '\n')"
      shell: bash
    - name: Install NodeJS
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ steps.detect-node.outputs.version }}
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - name: Restore Node Modules Cache
      id: node-modules-cache
      uses: actions/cache@v3.0.5
      with:
        path: |
          ./node_modules
          packages/*/node_modules
        key: ${{ steps.detect-node.outputs.version }}-${{ hashFiles('yarn.lock') }}
    - name: Install Yarn Project
      run: yarn install --immutable
      shell: bash
    - name: Create Artifacts Directory
      run: mkdir -p artifacts
      shell: bash
    - name: Configure Git
      run: |
        git config --global user.name tophat-opensource-bot
        git config --global user.email opensource-leads+bot@tophatmonocle.com
        git config --global init.defaultBranch master
      shell: bash
