name: docker-push
description: Push sanity runner service container image to Docker Hub
inputs:
  archivePath:
    description: Path to the saved docker image archive
    required: true
  project:
    description: name of sub project (client or service)
    required: true

steps:
  - name: Load docker archive
    run: docker load < ${{ inputs.archivePath }}
  -
    name: Login to GHCR
    uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
  - name: Publish the image to Docker Hub
    run: make -C ${{ inputs.project }} publish-docker
