name: docker-push
description: Push sanity runner service container image to Docker Hub
inputs:
  archivePath:
    description: Path to the saved docker image archive
    required: true
  project:
    description: name of sub project (client or service)
    required: true
  username:
    description: Username for docker registry
    required: true
  password:
    description: Password for docker registry
    required: true
steps:
  - name: Load docker archive
    run: docker load < ${{ inputs.archivePath }}
  - name: Log in to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
  - name: Publish the image to Docker Hub
    run: make -C ${{ inputs.project }} publish-docker
