name: Release

on:
  workflow_dispatch:

env:
  CI: 1
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
  DOCKER_BUILDKIT: 1

jobs:
  prerelease:
    name: "Prerelease"
    if: github.ref == 'refs/heads/next'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Prerelease
        run: yarn prerelease
        env:
          GH_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Images
        run: yarn workspaces foreach -vpt --no-private --topological-dev run docker:build
      - name: Tag Docker Images
        run: yarn workspaces foreach -vp run docker:tag
      - name: Tag Docker Images (Prerelease)
        run: yarn workspaces foreach -vp run docker:tag:prerelease
      - name: Publish Docker Images
        run: yarn workspaces foreach -vp run docker:push
      - name: Publish Docker Images (Prerelease)
        run: yarn workspaces foreach -vp run docker:push:prerelease
  release:
    name: Release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Release
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Images
        run: yarn workspaces foreach -vpt --no-private --topological-dev run docker:build
      - name: Tag Docker Images
        run: yarn workspaces foreach -vp run docker:tag
      - name: Publish Docker Images
        run: yarn workspaces foreach -vp run docker:push
      - name: Publish Docker Images (Latest)
        run: yarn workspaces foreach -vp run docker:push:latest
